title: RtBrick BNG Blaster
description: The BNG Blaster is a test tool to simulate thousands of PPPoE or IPoE subscribers including IPTV, traffic verification and convergence testing capabilities.
logo: images/rtbrick_logo.png
theme: jekyll-theme-minimal
